server:
  port: 8080          # Puerto en el que escuchará el micro de inventario

spring:
  application:
    name: ms-camarero-inventario   # Nombre con el que se registrará en Eureka

  datasource:
    url: jdbc:mysql://localhost:3306/dbinventario
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update             # crea/actualiza tablas automáticamente
    show-sql: true                 # muestra las consultas en consola

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
