server:
  port: 8083

spring:
  application:
    name: ms-camarero-pedidos

  datasource:
    url: jdbc:mysql://localhost:3306/dbpedidos
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mesas:
  service:
    url: http://localhost:8082/api
inventario:
  service:
    url: http://localhost:8084/inventario
notificaciones:
  service:
    url: http://localhost:8085/notificaciones
menu:
  service:
    url: http://localhost:8086/menu
facturacion:
  service:
    url: http://localhost:8087/facturacion

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true