server:
  port: 8088

spring:
  application:
    name: ms-camarero-analiticas
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

reservas:
  service:
    url: http://localhost:8082/api
pedidos:
  service:
    url: http://localhost:8083/pedidos
facturacion:
  service:
    url: http://localhost:8087/facturacion

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true